import { Injectable } from '@nestjs/common';
import { Doctor } from '../entities/doctor.entity';
import { IDoctorsRepository } from './doctors.repository.interface';

@Injectable()
export class InMemoryDoctorsRepository implements IDoctorsRepository {
  private readonly doctors: Doctor[] = [
    { id: 1,  name: 'Dra. Marina Lopes',      specialty: 'Cardiologia',  city: 'São Paulo, SP',       rating: 4.9, reviews: 212, price: 350, crm: 'CRM-SP 123456', telemedicine: true,  bio: 'Cardiologista com 14 anos de experiência.',                                          address: 'Av. Paulista, 1048 - Bela Vista' },
    { id: 2,  name: 'Dr. Carlos Mendes',       specialty: 'Cardiologia',  city: 'Rio de Janeiro, RJ',  rating: 4.7, reviews: 134, price: 320, crm: 'CRM-RJ 234567', telemedicine: true,  bio: 'Cardiologista especializado em insuficiência cardíaca.',                               address: 'R. Nossa Sra. de Copacabana, 800 - Copacabana' },
    { id: 3,  name: 'Dra. Ana Beatriz Rocha',  specialty: 'Cardiologia',  city: 'Belo Horizonte, MG',   rating: 4.8, reviews: 187, price: 280, crm: 'CRM-MG 345678', telemedicine: true,  bio: 'Cardiologista com foco em prevenção e check-up.',                                      address: 'Av. do Contorno, 6061 - Savassi' },
    { id: 4,  name: 'Dr. Eduardo Campos',      specialty: 'Cardiologia',  city: 'Curitiba, PR',        rating: 4.6, reviews:  98, price: 300, crm: 'CRM-PR 456789', telemedicine: true,  bio: 'Especialista em cardiologia intervencionista.',                                         address: 'R. XV de Novembro, 1200 - Centro' },
    { id: 5,  name: 'Dr. Rafael Andrade',      specialty: 'Dermatologia', city: 'São Paulo, SP',       rating: 4.8, reviews: 167, price: 290, crm: 'CRM-SP 654321', telemedicine: true,  bio: 'Especialista em dermatologia clínica e cirúrgica.',                                    address: 'R. Augusta, 2200 - Jardins' },
    { id: 6,  name: 'Dra. Juliana Torres',     specialty: 'Dermatologia', city: 'Salvador, BA',        rating: 4.9, reviews: 203, price: 260, crm: 'CRM-BA 567890', telemedicine: true,  bio: 'Dermatologista com experiência em laser e estética.',                                  address: 'Av. Oceânica, 1500 - Barra' },
    { id: 7,  name: 'Dr. Marcos Paulo Silva',  specialty: 'Dermatologia', city: 'Porto Alegre, RS',    rating: 4.5, reviews:  76, price: 250, crm: 'CRM-RS 678901', telemedicine: false, bio: 'Dermatologista focado em dermatologia pediátrica.',                                     address: 'R. Padre Chagas, 300 - Moinhos de Vento' },
    { id: 8,  name: 'Dra. Fernanda Costa',     specialty: 'Dermatologia', city: 'Brasília, DF',        rating: 4.7, reviews: 145, price: 310, crm: 'CRM-DF 789012', telemedicine: true,  bio: 'Especialista em dermatologia clínica e oncologia cutânea.',                             address: 'SHS Qd 6, Bloco C - Asa Sul' },
    { id: 9,  name: 'Dra. Camila Ferreira',    specialty: 'Psicologia',   city: 'Rio de Janeiro, RJ',  rating: 5.0, reviews: 340, price: 220, crm: 'CRP 05/98765', telemedicine: true,  bio: 'Psicóloga clínica com abordagem em TCC.',                                             address: 'R. Visconde de Pirajá, 414 - Ipanema' },
    { id: 10, name: 'Dr. Lucas Almeida',       specialty: 'Psicologia',   city: 'São Paulo, SP',       rating: 4.8, reviews: 198, price: 200, crm: 'CRP 06/54321', telemedicine: true,  bio: 'Psicólogo especializado em terapia de casal e familiar.',                              address: 'R. Haddock Lobo, 400 - Cerqueira César' },
    { id: 11, name: 'Dra. Roberta Martins',    specialty: 'Psicologia',   city: 'Recife, PE',          rating: 4.9, reviews: 267, price: 180, crm: 'CRP 02/11223', telemedicine: true,  bio: 'Psicóloga infantil com mais de 10 anos de experiência.',                               address: 'R. da Aurora, 500 - Boa Vista' },
    { id: 12, name: 'Dr. Thiago Oliveira',     specialty: 'Psicologia',   city: 'Florianópolis, SC',   rating: 4.6, reviews: 112, price: 240, crm: 'CRP 12/44556', telemedicine: false, bio: 'Psicólogo com abordagem existencial-humanista.',                                        address: 'R. Felipe Schmidt, 200 - Centro' },
    { id: 13, name: 'Dr. Bruno Carvalho',      specialty: 'Ortopedia',    city: 'Belo Horizonte, MG',  rating: 4.7, reviews:  98, price: 310, crm: 'CRM-MG 112233', telemedicine: false, bio: 'Ortopedista especializado em joelho e medicina esportiva.',                            address: 'Av. do Contorno, 6061 - Savassi' },
    { id: 14, name: 'Dr. Ricardo Santos',      specialty: 'Ortopedia',    city: 'São Paulo, SP',       rating: 4.8, reviews: 156, price: 340, crm: 'CRM-SP 223344', telemedicine: true,  bio: 'Especialista em coluna e cirurgia ortopédica minimamente invasiva.',                    address: 'Av. Brasil, 1500 - Jardim América' },
    { id: 15, name: 'Dra. Priscila Neves',     specialty: 'Ortopedia',    city: 'Curitiba, PR',        rating: 4.6, reviews:  84, price: 290, crm: 'CRM-PR 334455', telemedicine: true,  bio: 'Ortopedista com foco em traumatologia esportiva.',                                     address: 'R. Comendador Araújo, 500 - Centro' },
    { id: 16, name: 'Dr. Gustavo Rocha',       specialty: 'Ortopedia',    city: 'Goiânia, GO',         rating: 4.9, reviews: 221, price: 270, crm: 'CRM-GO 445566', telemedicine: true,  bio: 'Ortopedista especializado em quadril e reconstrução articular.',                       address: 'Av. T-63, 1000 - Nova Suíça' },
    { id: 17, name: 'Dra. Juliana Mota',       specialty: 'Pediatria',    city: 'São Paulo, SP',       rating: 4.9, reviews: 421, price: 280, crm: 'CRM-SP 778899', telemedicine: true,  bio: 'Pediatra dedicada ao acompanhamento integral da criança.',                             address: 'R. Oscar Freire, 379 - Pinheiros' },
    { id: 18, name: 'Dr. Pedro Henrique Lima', specialty: 'Pediatria',    city: 'Rio de Janeiro, RJ',  rating: 4.7, reviews: 189, price: 250, crm: 'CRM-RJ 889900', telemedicine: true,  bio: 'Pediatra com experiência em neonatologia e puericultura.',                             address: 'R. Barata Ribeiro, 500 - Copacabana' },
    { id: 19, name: 'Dra. Amanda Vieira',      specialty: 'Pediatria',    city: 'Fortaleza, CE',       rating: 4.8, reviews: 310, price: 230, crm: 'CRM-CE 990011', telemedicine: true,  bio: 'Pediatra especializada em alergias e imunologia infantil.',                            address: 'Av. Beira Mar, 2000 - Meireles' },
    { id: 20, name: 'Dr. Fábio Nogueira',      specialty: 'Pediatria',    city: 'Porto Alegre, RS',    rating: 4.5, reviews:  67, price: 260, crm: 'CRM-RS 100122', telemedicine: false, bio: 'Pediatra com foco em medicina do adolescente.',                                          address: 'R. Mostardeiro, 700 - Moinhos de Vento' },
    { id: 21, name: 'Dr. Fernando Martins',    specialty: 'Ginecologia',  city: 'Curitiba, PR',        rating: 4.8, reviews: 189, price: 300, crm: 'CRM-PR 445566', telemedicine: false, bio: 'Ginecologista e obstetra com foco em saúde da mulher.',                              address: 'Al. Dr. Carlos de Carvalho, 555 - Centro' },
    { id: 22, name: 'Dra. Cristiane Barbosa',  specialty: 'Ginecologia',  city: 'São Paulo, SP',       rating: 4.9, reviews: 245, price: 350, crm: 'CRM-SP 556677', telemedicine: true,  bio: 'Ginecologista especializada em reprodução assistida.',                                 address: 'R. Bela Cintra, 800 - Consolação' },
    { id: 23, name: 'Dra. Renata Oliveira',    specialty: 'Ginecologia',  city: 'Salvador, BA',        rating: 4.7, reviews: 132, price: 270, crm: 'CRM-BA 667788', telemedicine: true,  bio: 'Ginecologista com foco em menopausa e climatério.',                                    address: 'R. Marques de Caravelas, 400 - Barra' },
    { id: 24, name: 'Dr. André Luiz Castro',   specialty: 'Ginecologia',  city: 'Brasília, DF',        rating: 4.6, reviews:  91, price: 310, crm: 'CRM-DF 778899', telemedicine: true,  bio: 'Ginecologista especializado em laparoscopia ginecológica.',                             address: 'SHS Qd 2, Bloco D - Asa Sul' },
    { id: 25, name: 'Dr. Marcelo Augusto',     specialty: 'Neurologia',   city: 'São Paulo, SP',       rating: 4.8, reviews: 178, price: 380, crm: 'CRM-SP 889900', telemedicine: true,  bio: 'Neurologista especializado em cefaleia e distúrbios do movimento.',                   address: 'Av. Rebolças, 3000 - Pinheiros' },
    { id: 26, name: 'Dra. Tânia Reis',         specialty: 'Neurologia',   city: 'Rio de Janeiro, RJ',  rating: 4.9, reviews: 214, price: 360, crm: 'CRM-RJ 990011', telemedicine: true,  bio: 'Neurologista com experiência em doenças neurodegenerativas.',                          address: 'R. Humaitá, 800 - Humaitá' },
    { id: 27, name: 'Dr. Sérgio Mello',        specialty: 'Neurologia',   city: 'Belo Horizonte, MG',  rating: 4.7, reviews: 103, price: 330, crm: 'CRM-MG 100233', telemedicine: true,  bio: 'Neurologista especializado em epilepsia e distúrbios do sono.',                         address: 'R. Alvarenga Peixoto, 450 - Santo Agostinho' },
    { id: 28, name: 'Dra. Patrícia Duarte',    specialty: 'Neurologia',   city: 'Recife, PE',          rating: 4.6, reviews:  88, price: 290, crm: 'CRM-PE 200344', telemedicine: false, bio: 'Neurologista com foco em medicina vascular cerebral.',                                  address: 'R. do Príncipe, 600 - Boa Vista' },
    { id: 29, name: 'Dr. Daniel Figueiredo',   specialty: 'Oftalmologia', city: 'São Paulo, SP',       rating: 4.9, reviews: 312, price: 340, crm: 'CRM-SP 300455', telemedicine: true,  bio: 'Oftalmologista especializado em cirurgia refrativa e catarata.',                       address: 'Av. Ibirapuera, 2000 - Indianópolis' },
    { id: 30, name: 'Dra. Laura Campos',       specialty: 'Oftalmologia', city: 'Curitiba, PR',        rating: 4.8, reviews: 167, price: 310, crm: 'CRM-PR 400566', telemedicine: true,  bio: 'Oftalmologista com foco em retina e vítreo.',                                         address: 'R. Visconde do Rio Branco, 800 - Centro' },
    { id: 31, name: 'Dr. Vinícius Teixeira',   specialty: 'Oftalmologia', city: 'Manaus, AM',          rating: 4.5, reviews:  74, price: 260, crm: 'CRM-AM 500677', telemedicine: false, bio: 'Oftalmologista especializado em glaucoma e estrabismo.',                                address: 'Av. Eduardo Ribeiro, 300 - Centro' },
    { id: 32, name: 'Dra. Eliane Martins',     specialty: 'Oftalmologia', city: 'Florianópolis, SC',   rating: 4.7, reviews: 129, price: 300, crm: 'CRM-SC 600788', telemedicine: true,  bio: 'Oftalmologista com experiência em córnea e lentes de contato.',                        address: 'R. Tenente Silveira, 150 - Centro' },
    { id: 33, name: 'Dr. Leandro Vieira',      specialty: 'Psiquiatria',  city: 'São Paulo, SP',       rating: 4.8, reviews: 198, price: 400, crm: 'CRM-SP 700899', telemedicine: true,  bio: 'Psiquiatra especializado em transtornos de ansiedade e depressão.',                   address: 'R. Estados Unidos, 1200 - Jardins' },
    { id: 34, name: 'Dra. Simone Rocha',       specialty: 'Psiquiatria',  city: 'Porto Alegre, RS',    rating: 4.9, reviews: 234, price: 370, crm: 'CRM-RS 800900', telemedicine: true,  bio: 'Psiquiatra com experiência em transtorno bipolar e TDAH.',                             address: 'R. Padre Chagas, 250 - Moinhos de Vento' },
    { id: 35, name: 'Dr. Felipe Araújo',       specialty: 'Psiquiatria',  city: 'Brasília, DF',        rating: 4.6, reviews:  95, price: 350, crm: 'CRM-DF 900011', telemedicine: true,  bio: 'Psiquiatra especializado em dependência química.',                                     address: 'SHS Qd 5, Bloco A - Asa Sul' },
    { id: 36, name: 'Dra. Cintia Xavier',      specialty: 'Psiquiatria',  city: 'Salvador, BA',        rating: 4.7, reviews: 142, price: 320, crm: 'CRM-BA 100122', telemedicine: true,  bio: 'Psiquiatra com foco em saúde mental da mulher.',                                       address: 'R. da Grécia, 300 - Pituba' },
    { id: 37, name: 'Dr. Ricardo Barbosa',     specialty: 'Reumatologia', city: 'São Paulo, SP',       rating: 4.7, reviews: 111, price: 330, crm: 'CRM-SP 200233', telemedicine: true,  bio: 'Reumatologista especializado em artrite reumatoide e lúpus.',                          address: 'R. Tabapuã, 800 - Itaim Bibi' },
    { id: 38, name: 'Dra. Helena Dias',        specialty: 'Reumatologia', city: 'Belo Horizonte, MG',  rating: 4.8, reviews: 156, price: 290, crm: 'CRM-MG 300344', telemedicine: true,  bio: 'Reumatologista com experiência em osteoporose e gota.',                                address: 'Av. Prudente de Morais, 900 - Santo Antônio' },
    { id: 39, name: 'Dr. José Renato Lima',    specialty: 'Reumatologia', city: 'Goiânia, GO',          rating: 4.5, reviews:  68, price: 280, crm: 'CRM-GO 400455', telemedicine: false, bio: 'Reumatologista especializado em fibromialgia.',                                        address: 'Av. T-2, 500 - Setor Bueno' },
    { id: 40, name: 'Dra. Camila Oliveira',    specialty: 'Reumatologia', city: 'Curitiba, PR',        rating: 4.6, reviews:  87, price: 310, crm: 'CRM-PR 500566', telemedicine: true,  bio: 'Reumatologista com foco em espondiloartrites.',                                       address: 'R. Emiliano Perneta, 600 - Centro' },
    { id: 41, name: 'Dr. Rogério Silva',       specialty: 'Urologia',     city: 'São Paulo, SP',       rating: 4.8, reviews: 175, price: 360, crm: 'CRM-SP 600677', telemedicine: true,  bio: 'Urologista especializado em cirurgia robótica e câncer de próstata.',                  address: 'Av. Albert Einstein, 500 - Morumbi' },
    { id: 42, name: 'Dr. Renato Moreira',      specialty: 'Urologia',     city: 'Rio de Janeiro, RJ',  rating: 4.7, reviews: 123, price: 340, crm: 'CRM-RJ 700788', telemedicine: true,  bio: 'Urologista com experiência em litíase urinária e disfunção erétil.',                   address: 'R. Sorocaba, 500 - Botafogo' },
    { id: 43, name: 'Dra. Isabela Nunes',      specialty: 'Urologia',     city: 'Recife, PE',          rating: 4.9, reviews: 208, price: 300, crm: 'CRM-PE 800899', telemedicine: true,  bio: 'Urologista especializada em uroginecologia e incontinência urinária.',                  address: 'R. do Hospício, 400 - Boa Vista' },
    { id: 44, name: 'Dr. Otávio Farias',       specialty: 'Urologia',     city: 'Porto Alegre, RS',    rating: 4.6, reviews:  96, price: 320, crm: 'CRM-RS 900900', telemedicine: false, bio: 'Urologista com foco em andrologia e fertilidade masculina.',                            address: 'R. Hilário Ribeiro, 200 - Petrópolis' },
  ];

  async findAll(): Promise<Doctor[]> {
    return this.doctors;
  }

  async findById(id: number): Promise<Doctor | null> {
    return this.doctors.find((d) => d.id === id) ?? null;
  }
}
